services:
  - type: web
    name: qadiyat-alqasr
    runtime: static
    buildCommand: 'true'
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
